# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana:5.5.2

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
# RUN kibana-plugin install x-pack
# ADD searchguard-kibana-5.5.2-4.zip /searchguard-kibana-5.5.2-4.zip
# RUN kibana-plugin install file:///searchguard-kibana-5.5.2-4.zip